#!/bin/bash

if ! [[ -e llvm2c ]]; then
	echo "llvm2c not found!"
	exit 1
fi

./run_loops
echo
./run_math
echo
./run_asm
echo
./run_struct
echo
./run_pointer
echo
./run_branching
echo
./run_statements